### ISSUE TITLE
Font size changes don't register after upgrade to 1.2

### ISSUE THREAD

**Issue by darekrusin** [mikekazakov/nc#61]
I just got the automatic upgrade, tried changing font sizes and nothing worked. I was getting frustrated, restarted the app, nothing. Then I happened to click here and pick "modern" from the menu again (it was modern before, so the only effective action was a click) and suddenly everything snapped and all my previous changes became visible.

![image](https://cloud.githubusercontent.com/assets/8372873/23585184/b40a4608-0177-11e7-9ffe-f8a89b46fa90.png)

Now my changes register immediately. Maybe I had some old data in the previous version's config that were conflicting. I just wanted to let you know, because it's strange that clicking that drop down list made that kind of change.

**Comment by mikekazakov** [comment]
Darek, I believe this issue was inducted by remains of previous preview build(s).
At some some the built-in themes were named "modern", "classic" etc, and perhaps this value was stored in your custom config. Later on, these themes where renamed with capital letter in front: "Modern" etc.
So maybe v1.2.0 was confused by invalid setting - an absent theme was "selected" by custom config.
If such violation happens, the fallback mechanism is to simply use values from "Modern" theme.
So it make sense that after re-assigning current theme all backs to normal functioning.

**Comment by darekrusin** [comment]
I see. In that case, it shouldn't affect regular users so I think you can close the issue.
